# Generated by Django 3.2 on 2023-07-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Content', max_length=250)),
                ('date_time', models.DateTimeField(blank=True, db_column='Date_Time', null=True)),
                ('replyid', models.IntegerField(blank=True, db_column='ReplyID', null=True)),
            ],
            options={
                'db_table': 'COMMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CriticsSuggestions',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Content', max_length=1000)),
                ('score', models.IntegerField(blank=True, db_column='Score', null=True)),
            ],
            options={
                'db_table': 'CRITICS_SUGGESTIONS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('entrydate', models.DateField(db_column='EntryDate')),
                ('device_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Device_name', max_length=25)),
            ],
            options={
                'db_table': 'Device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='_Name', max_length=25)),
                ('explanation', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Explanation', max_length=1000, null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('currency', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Currency', max_length=10, null=True)),
                ('capacity', models.IntegerField(db_column='Capacity')),
                ('picture', models.BinaryField(blank=True, db_column='Picture', max_length='max', null=True)),
                ('releasedate', models.DateField(db_column='ReleaseDate')),
                ('operatingsystem', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='OperatingSystem', max_length=10)),
                ('field_version', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='_Version', max_length=10)),
                ('downloadnumber', models.IntegerField(blank=True, db_column='DownloadNumber', null=True)),
                ('category1', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Category1', max_length=25)),
                ('category2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Category2', max_length=25, null=True)),
                ('totalscore', models.BigIntegerField(blank=True, db_column='TotalScore', null=True)),
            ],
            options={
                'db_table': 'SOFTWARE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserName', max_length=25, primary_key=True, serialize=False)),
                ('balancenumber', models.FloatField(blank=True, db_column='BalanceNumber', null=True)),
                ('balancecurrency', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BalanceCurrency', max_length=10)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=50, null=True)),
                ('field_password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='_Password', max_length=33)),
                ('gender', models.BooleanField(db_column='Gender')),
                ('birthdate_day', models.IntegerField(db_column='BirthDate_Day')),
                ('birthdate_month', models.IntegerField(db_column='BirthDate_Month')),
                ('birthdate_year', models.IntegerField(db_column='BirthDate_Year')),
                ('phonenumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNumber', max_length=11)),
            ],
            options={
                'db_table': '_User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producer_uname', models.OneToOneField(db_column='Producer_UName', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DownloadSoftwareSystem.user')),
            ],
            options={
                'db_table': 'PRODUCER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regular',
            fields=[
                ('regular_uname', models.OneToOneField(db_column='Regular_UName', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DownloadSoftwareSystem.user')),
            ],
            options={
                'db_table': 'REGULAR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('regular_uname', models.OneToOneField(db_column='Regular_UName', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DownloadSoftwareSystem.regular')),
                ('buy_time', models.DateTimeField(blank=True, db_column='Buy_Time', null=True)),
            ],
            options={
                'db_table': 'BUY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Downloaded',
            fields=[
                ('regular_uname', models.OneToOneField(db_column='Regular_UName', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DownloadSoftwareSystem.regular')),
                ('downloadid', models.IntegerField(db_column='DownloadID')),
            ],
            options={
                'db_table': 'DOWNLOADED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marked',
            fields=[
                ('regular_uname', models.OneToOneField(db_column='Regular_UName', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DownloadSoftwareSystem.regular')),
            ],
            options={
                'db_table': 'MARKED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('scorevalue', models.IntegerField(db_column='ScoreValue')),
                ('regular_uname', models.OneToOneField(db_column='Regular_UName', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DownloadSoftwareSystem.regular')),
            ],
            options={
                'db_table': 'SCORE',
                'managed': False,
            },
        ),
    ]
